### PR TITLE
Switch to console.time for perf measurements

### LINKED ISSUE #13: stopwatch.js should use console.time()/timeEnd()
if so, you'd get these segments marked up in the Timeline profile. 

image

### PR DESCRIPTION
**Pull request by samccone**
Fixes #13 

By using this new way, not only do we get the same logs in the console, but we also get awesome timeline markers :tada: 

screen shot 2015-11-25 at 12 31 48 pm

screen shot 2015-11-25 at 12 40 27 pm
screen shot 2015-11-25 at 12 40 17 pm

Awesome job on this PS :clap:

### CODE REVIEW

**Comment by paulirish** [comment]
Ooh this nice.

**Comment by nolanlawson** [comment]
Awesome, thank you! `console.time()` is definitely more appropriate than `console.log()` for this.

**Comment by nolanlawson** [comment]
4c5be4e5c71ef685c4e6fdf43bcd102326c224fe

**Comment by samccone** [comment]
:bow:

**Comment by paulirish** [comment]
Nice work, sam!

**Pull request closed without merging**
