### PR TITLE
Swap unicode ☰ for an SVG icon

### LINKED ISSUE #16: Swap unicode ☰ for an SVG icon
It doesn't show up properly on some Android devices. Also gotta make sure the size stays consistent with the back button arrow.

### PR DESCRIPTION
**Pull request by mhartington**
Adds a nice svg icon. 

Closes #16

### CODE REVIEW

**Comment by nickcolley** [comment]
If you want to optimize the SVG you can run it through https://github.com/svg/svgo (https://jakearchibald.github.io/svgomg/)

Also since it's such a small SVG you could inline it directly into the html to remove the extra request.

**Comment by nickcolley** [comment]
Actually thinking about it, @nolanlawson I don't think you need a hamburger slide draw at all. You only have one link in there for about, you could put that somewhere else and remove all dependencies for the side menu.

Just a thought.

**Comment by mhartington** [comment]
Done. 

That is true, the sidemenu could be done away with all together

**Comment by nolanlawson** [comment]
Awesome, thank you for the PR! Yeah, I only put in the side menu because: 

1. Inertia (it was already in the MUI template), and
2. Eventually I want users to be able to toggle between a list of moves and a list of Pokémon, in which case the side menu will actually have a purpose

So don't worry; this PR is much appreciated, and that side menu isn't going anywhere for the time being. :)

**Comment by nolanlawson** [comment]
b609996f10c0dffada09fa67dde891c304a9a336 and 6d99e77ecbc0ececa1c18ca25a03ea22527ea5f2. cheers and thanks a ton!!

**Comment by nickcolley** [comment]
@nolanlawson there might be a better place to put it than behind a burger, ping me in an issue if you want later. :+1: 

Great article explaining my thoughts http://www.lukew.com/ff/entry.asp?1945

**Comment by nolanlawson** [comment]
I know I know, I agree that hamburger/sidemenus are out of vogue now. I totally understand why.

Another reason I planned on keeping the side menu is because it felt like a nice challenge to me to actually make a 60fps swipeable version. I want to make something like https://voice-memos.appspot.com/ but with progressive darkening/lightening of the background (ala many Android native apps).

**Comment by nickcolley** [comment]
I guess it's up to you to determine if your users are pokemon fans or techincal demo folks. :+1:

**Comment by nolanlawson** [comment]
Hahaha yeah, I am kinda serving two masters with this thing.

**Pull request closed without merging**
