### PR TITLE
[ISSUE 7, 8] prevents mobile scrolling with fixed detail overlay

### LINKED ISSUE #7: iOS can scroll main list while detail view is visible
Reported on Twitter: https://twitter.com/djbriane/status/669232271505817600?s=09

### PR DESCRIPTION
**Pull request by djrosenbaum**
Fixes #7 #8 

Prevents scrolling on mobile iOS from Detail View

### CODE REVIEW

**Comment by djrosenbaum** [comment]
This pull request fixes a bug on iphone preventing the background from scrolling in safari when the fixed position detail overlay is displayed.

**Comment by nolanlawson** [comment]
Thanks, LGTM!

**Comment by nolanlawson** [comment]
Changes are now live, also @djrosenbaum you are now a collaborator. :) Feel free to push minor changes yourself or @-mention me for big stuff if you still want a review.

**Comment by nolanlawson** [comment]
FWIW I don't have big plans for Pokedex at this time; I'd like to get scrolling fixed on the main view in iOS but I'm also kinda hoping Safari might fix it themselves. Other than that the next big thing is probably updating to the pokeapi v2 data which is a huge undertaking especially because it probably also necessitates a rewrite of the PouchDB logic to actually allow syncing instead of using pouchdb-load for everything.

**Comment by tnguyen14** [comment]
@nolanlawson do you have anything started for the migration to pokeapi v2? wondering if there's something I could help with here.

**Comment by nolanlawson** [comment]
I've decided to un-maintain this project. The v2 migration would be an enormous amount of work, and I don't have the energy to undertake it. The point of this project was to show what could be done with good performance best practices and emerging PWA technologies.

If someone else would like to undertake the work, please go ahead and fork but I'd prefer to keep `pokedex.org` as-is at least for the near future. :)

**Pull request merged**
